# Generated by Django 3.0.4 on 2020-05-08 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_text',
            new_name='description',
        ),
    ]
